services:
  openhands:
    image: 'ghcr.io/openhands/openhands:latest'
    environment:
      - AGENT_SERVER_IMAGE_REPOSITORY=ghcr.io/openhands/agent-server
      - AGENT_SERVER_IMAGE_TAG=1.26.0-python
      - TZ=Asia/Ho_Chi_Minh
      - LOG_ALL_EVENTS=true
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - 'openhands-state:/.openhands'
      - '/var/run/docker.sock:/var/run/docker.sock'
volumes:
  openhands-state:
